apiVersion: v1
kind: Service
metadata:
  name: devops-app-service
  namespace: monitoring
  labels:
    app: devops-app
spec:
  type: NodePort
  selector:
    app: devops-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
      protocol: TCP
      name: http